#!/bin/bash

module load openmpi/1.8.4-icc
module load intel/15.0.090

MPI_CC=mpicxx
NAME_EXE=fil.e

$MPI_CC parameters.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC output.cpp -c -std=c++11
$MPI_CC dispersion.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC initialization.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC calculation.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC propagation.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC finalization.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib
$MPI_CC main.cpp -c -std=c++11 -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib

$MPI_CC parameters.o output.o dispersion.o initialization.o calculation.o propagation.o finalization.o main.o -o $NAME_EXE -I/home/users/dergachev/local/include -L/home/users/dergachev/local/lib -lfftw_mpi -lfftw

rm -rf *.o